### ISSUE TITLE
config/initializers/passbook.rb:9:in `block in <top (required)>': undefined method `p12_cert=' for Passbook:Module (NoMethodError)

### ISSUE THREAD

**Issue by fahimbabarpatel** [frozon/passbook#49]
Hello All,

I followed below steps:-
1. Added gem in Gemfile and installed it.
2. rails g passbook:config
3. Passbook.configure do |passbook|
      passbook.wwdc_cert = Rails.root.join('my.pem')
      passbook.p12_certificate = Rails.root.join('my.p12')
      passbook.p12_password = 'my_password'
    end 

Once I start server then facing below error:-

#### config/initializers/passbook.rb:9:in `block in <top (required)>': undefined method `p12_cert=' for Passbook:Module (NoMethodError)

Thanks! in advance.

**Comment by frozon** [comment]
Seems you have some trouble with the initializer it self.
Are you sure that you use passbook.p12_certificate and not passbook.p12_cert?

**Comment by fahimbabarpatel** [comment]
Thanks ! 

I changed passbook.p12_cert to passbook.p12_certificate and it worked.
