### ISSUE TITLE
The pass "pass.pkpass" could not be opened

### ISSUE THREAD

**Issue by pauldd91** [frozon/passbook#51]
I keep getting this error: The pass "pass.pkpass" could not be opened. Below's my code. I've re-done the cert process like 3 times. Not sure where it's failing because the package seems intact. 

```ruby
def show
   pass = Pass.find(params[:id])
   pass_path = ENV['passes_folder_path'] + "/passes/#{pass.id}"
   pass_json = File.read(pass_path + "/pass.json")
   pkpass = Passbook::PKPass.new pass_json
   files = []
   Dir.foreach(pass_path) do |file|
     next if file == '.' or file == '..' or file == '.DS_Store'
     files << file
   end
   pkpass.addFiles files
   send_data(pkpass, type: 'application/vnd.apple.pkpass', disposition: 'attachment', filename: 'pass.pkpass', status: 201, location: [:api, pass])
 end
```

**Comment by frozon** [comment]
You can not send pkpass as is in send_data
You have to call ```pkpass.file.path``` which will return the temporary pkpass file path

Sorry it could be a little bit more documented. Will update doc in order to get that a bit more clear.

Let me know if it solved your issue.

**Comment by pauldd91** [comment]
WOW! thanks for the prompt response. That still returns ```nil``` for me.

**Comment by pauldd91** [comment]
![screen shot 2015-07-17 at 10 33 30 am](https://cloud.githubusercontent.com/assets/3650761/8749411/59c27dd4-2c6f-11e5-9fc1-97b7698f5998.png)

**Comment by frozon** [comment]
This time it is something different. You are only giving the filename and not the file path.

```ruby
Dir.foreach(pass_path) do |file|
  next if file == '.' or file == '..' or file == '.DS_Store'
  files << File.join(pass_path, file)
end
```

This should solve this other issue.

**Comment by pauldd91** [comment]
ah! okay. I'll. Worked like a charm! BTW, I'd love to help with documentation and contributing.

**Comment by rmosolgo** [comment]
I'm sending pkpass responses like this:

```ruby 
pkpass = Passbook::PKPass.new # ... initialize & add files
send_data(pkpass.stream.string, filename: "pass.pkpass", content_type: "application/vnd.apple.pkpass") 
```
