### ISSUE TITLE
where to obtain notification_cert.pem

### ISSUE THREAD

**Issue by hshar7** [frozon/passbook#62]
My apologies about the noob questions, where can I obtain the notification_cert.pem cert?

**Comment by frozon** [comment]
Hi @hshar7 you'll find all informations about certs there [https://developer.apple.com/support/certificates/](https://developer.apple.com/support/certificates/)

Hope this will help

**Comment by hshar7** [comment]
@frozon Trying to read that but I am really not sure where to get a push notification cert for a pass.. if we don't have a separate app that interacts with the pass it wouldn't need a push cert, right?

**Comment by frozon** [comment]
Push certs is needed if you need to actually push info/update to the device on which the cert is installed.
If you do not plan to do so, then no, you don't need push certs.

**Comment by hshar7** [comment]
Oooh finally got it now :) thanks!
To clarify for everyone else, you can update the pass and have the new version ready to be served when the user requests the update (by refreshing the pass)
However, if you need to immediately update the card using push notification you will need to setup a separate app through Apple Developer account and have that cert included in the pass.
