### ISSUE TITLE
Can't open .pkpass file

### ISSUE THREAD

**Issue by dylanbromby** [frozon/passbook#72]
We've been using this gem for a few years, but suddenly we're unable to open generated .pkpass files and all we've done is generated a new Pass Type certificate from Apple. Has anyone else had any issues lately?

**Comment by rmdydo** [comment]
We recently started getting the following error: "The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified."
Same error?

**Comment by dylanbromby** [comment]
It was a certificate/signing bug on Apple's side. We had a brief email exchange with senior leadership about it after we concluded we'd exhausted all possible issues on our end. Here's a snippet from 2/11/20:

> The issue with the Certificate generation was found yesterday. It has been present for several days. It was fixed yesterday. 

Regenerate your cert and you should be fine.

**Comment by dylanbromby** [comment]
Closing this out since it was a bug with Apple's certificate signing.
